package proyecto_grafo;
/*
 * tabla_adyacencia.java
 *
 * Created on 31 de octubre de 2008, 20:08
 */

import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author  Administrador
 */
public class tabla_adyacencia extends javax.swing.JPanel {

    private ListSelectionModel list;
    private Table_mod dataModel;

    /**
     * elimina la posicion "i" de la tabla 
     * tanto fila como columna
     * @param i
     */
    public void elimiar(int i) {
        TableColumnModel modo_coulumna = Matriz_V.getColumnModel();
        TableColumn la_columna = modo_coulumna.getColumn(i + 1);
        Matriz_V.removeColumn(la_columna);
        dataModel.removeElementAt(i);
    }

    /**
     * elimina cada uno de los elemento 
     * en la tabla y fila
     */
    public void eliminar_All() {
        int i = this.dataModel.size();
        while (i > 0) {
            i--;
            elimiar(i);

        }
    }

    
    public Table_mod getDataModel() {
        return dataModel;
    }

    public void setDataModel() {
        this.dataModel = new Table_mod();
    }

    /**
     * añade u data file al data mode
     * @param v
     */
    public void add(data_fila v) {
        this.dataModel.addElement(v);
        TableColumn columna = new TableColumn(dataModel.size());
        columna.setResizable(true);
        this.Matriz_V.addColumn(columna);
    }

    /**
     * elimina todas las columnas de la tabla
     * 
     */
    public void removeAllElements() {
        int h = Matriz_V.getColumnCount();
        if (h == 1) {
            return;
        }
        System.out.println(h);
        for (int i = 1; i < h; ++i) {
            TableColumnModel modo_coulumna = Matriz_V.getColumnModel();
            TableColumn la_columna = modo_coulumna.getColumn(i);
            Matriz_V.removeColumn(la_columna);

        }
        dataModel.removeAllElements();
    }

    /** Creates new form tabla_adyacencia */
    public tabla_adyacencia() {
        this.dataModel = new Table_mod();
        initComponents();
        this.list_V.setModel(dataModel);
        this.Matriz_V.setModel(dataModel);
        this.list = list_V.getSelectionModel();
        this.Matriz_V.setSelectionModel(list);
        this.list.addListSelectionListener(new Select_evt(dataModel, list_V, Text));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_V = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Matriz_V = new javax.swing.JTable();

        Text.setFont(new java.awt.Font("Arial Black", 1, 11));
        Text.setText("Vertice");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Vertices"));

        list_V.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_V.setCellRenderer(new ver_bien_list());
        jScrollPane1.setViewportView(list_V);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matris Adyacencia"));

        Matriz_V.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Matriz_V.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Matriz_V);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addGap(566, 566, 566))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Matriz_V;
    private javax.swing.JLabel Text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList list_V;
    // End of variables declaration//GEN-END:variables
}
