package proyecto_grafo;

import java.awt.Component;


/*
 * Ventana.java
 *
 * Created on 2 de noviembre de 2008, 17:06
 */
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrador
 */
public class Ventana extends javax.swing.JFrame {

    /** Creates new form Ventana */
    public Ventana() {
        initComponents();
        this.tipos.add(GD_C);
        this.tipos.add(GD_S);
        this.tipos.add(GND_C);
        this.tipos.add(GND_S);
        this.panel.setArea_text(text);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipos = new javax.swing.ButtonGroup();
        paneles = new javax.swing.JTabbedPane();
        panel = new proyecto_grafo.Panel_dibujo();
        table_panel1 = new proyecto_grafo.tabla_adyacencia();
        table_incide1 = new proyecto_grafo.table_incidencia();
        jPanel1 = new javax.swing.JPanel();
        GND_S = new javax.swing.JRadioButton();
        GND_C = new javax.swing.JRadioButton();
        GD_S = new javax.swing.JRadioButton();
        GD_C = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Recorridos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        Recorridos1 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Ladilla"); // NOI18N
        setResizable(false);

        paneles.setForeground(new java.awt.Color(51, 51, 0));
        paneles.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        paneles.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cambio_de_paneles(evt);
            }
        });
        paneles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                escuchador_borrar_vertice(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        paneles.addTab("Lista Adyacencia", panel);
        paneles.addTab("Matriz Adyacencia", table_panel1);
        paneles.addTab("Matriz de inicidencia", table_incide1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tipo de Grado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        GND_S.setSelected(true);
        GND_S.setText("Grafo no dirigido sin peso");
        GND_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grafo_no_dirigido_sin_peso(evt);
            }
        });

        GND_C.setText("Grafo no dirigido con peso");
        GND_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grafo_no_dirigido_con_peso(evt);
            }
        });

        GD_S.setText("Grafo dirigido sin peso");
        GD_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grafo_dirigido_sin_peso(evt);
            }
        });

        GD_C.setText("Grafo dirigido con peso");
        GD_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grafo_dirigido_con_peso(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GND_S)
                    .addComponent(GND_C)
                    .addComponent(GD_S)
                    .addComponent(GD_C))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(GND_S)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GND_C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GD_S)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GD_C)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menu");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Menu");
        jMenuBar1.add(jMenu4);

        text.setColumns(10);
        text.setEditable(false);
        text.setFont(new java.awt.Font("Arial Black", 1, 14));
        text.setForeground(new java.awt.Color(0, 0, 255));
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        jMenu5.setText("File");

        jMenuItem4.setText("Nuevo");
        jMenu5.add(jMenuItem4);
        jMenu5.add(jSeparator2);
        jMenu5.add(jSeparator3);

        jMenuItem7.setText("Abrir Xml");
        jMenu5.add(jMenuItem7);

        jMenuItem5.setText("Salir");
        jMenu5.add(jMenuItem5);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("tipo de Grafo");

        jMenuItem1.setText("Es Conexo");
        jMenu6.add(jMenuItem1);

        jMenuItem3.setText("Existe Ciclo");
        jMenu6.add(jMenuItem3);

        jMenuBar2.add(jMenu6);

        Recorridos.setText("Recorridos");

        jMenuItem2.setText("En Profundida");
        Recorridos.add(jMenuItem2);
        Recorridos.add(jSeparator1);

        jMenuItem6.setText("En Anchura");
        Recorridos.add(jMenuItem6);

        jMenuBar2.add(Recorridos);

        jMenu8.setText("Menu");
        jMenuBar2.add(jMenu8);

        jMenu7.setText("Archivo");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Nuevo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crea_nueno_grafo(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Guardar");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarda_el_grafo_en_xml(evt);
            }
        });
        jMenu7.add(jMenuItem15);
        jMenu7.add(jSeparator4);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Abrir Xml");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abre_el_grafo_del_xml(evt);
            }
        });
        jMenu7.add(jMenuItem9);
        jMenu7.add(jSeparator5);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem10.setText("Salir");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adios(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuBar3.add(jMenu7);

        jMenu9.setText("tipo de Grafo");

        jMenuItem11.setText("Es Conexo");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifico_si_conexo(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuItem12.setText("Existe Ciclo");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existe_algun_ciclo(evt);
            }
        });
        jMenu9.add(jMenuItem12);

        jMenuBar3.add(jMenu9);

        Recorridos1.setText("Recorridos");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setText("En Profundida");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llama_al_recorrido_profundida_del_grafo(evt);
            }
        });
        Recorridos1.add(jMenuItem13);
        Recorridos1.add(jSeparator6);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("En Anchura");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llama_al_recorrido_anchura_del_grafo(evt);
            }
        });
        Recorridos1.add(jMenuItem14);

        jMenuBar3.add(Recorridos1);

        jMenu10.setText("Numero De Objeto");

        jMenuItem17.setText("Numero de Vertices");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_de_vertices(evt);
            }
        });
        jMenu10.add(jMenuItem17);

        jMenuItem16.setText("Numero de Aristas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_de_aristas(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuBar3.add(jMenu10);

        jMenu11.setText("Medidas");

        jMenuItem18.setText("Execentricidad de un Vertices");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculo_la_exentricidad_del_vertice(evt);
            }
        });
        jMenu11.add(jMenuItem18);

        jMenuItem19.setText("El diametro del grafo");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el_diametro_del_grafo(evt);
            }
        });
        jMenu11.add(jMenuItem19);

        jMenuItem20.setText("Dado dos vértices, obtener la distancia.");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la_distancia_entre_2_vertices(evt);
            }
        });
        jMenu11.add(jMenuItem20);

        jMenuBar3.add(jMenu11);

        jMenu12.setText("Buscar");

        jMenuItem21.setText("Nodos con un grado en particular. ");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busco_vertice_con_ese_grado(evt);
            }
        });
        jMenu12.add(jMenuItem21);

        jMenuItem22.setText("Existencia de caminos");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifico_si_hay_un_camino_entre_2_vertice(evt);
            }
        });
        jMenu12.add(jMenuItem22);

        jMenuBar3.add(jMenu12);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cambio_de_paneles(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cambio_de_paneles

    Component h = paneles.getSelectedComponent();

    if (h == table_panel1) {
        pasar_a_matriz_adyacencia();
    } else if (h == table_incide1) {
        pasar_a_matriz_incidecia();
    }

}//GEN-LAST:event_cambio_de_paneles

private void escuchador_borrar_vertice(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_escuchador_borrar_vertice
    panel.eliminar(evt);
}//GEN-LAST:event_escuchador_borrar_vertice

private void Grafo_no_dirigido_sin_peso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grafo_no_dirigido_sin_peso
    panel.setTipo_grafo(1);
}//GEN-LAST:event_Grafo_no_dirigido_sin_peso

private void Grafo_no_dirigido_con_peso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grafo_no_dirigido_con_peso
    panel.setTipo_grafo(2);
}//GEN-LAST:event_Grafo_no_dirigido_con_peso

private void Grafo_dirigido_sin_peso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grafo_dirigido_sin_peso
    panel.setTipo_grafo(3);
}//GEN-LAST:event_Grafo_dirigido_sin_peso

private void Grafo_dirigido_con_peso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grafo_dirigido_con_peso
    panel.setTipo_grafo(4);
}//GEN-LAST:event_Grafo_dirigido_con_peso

private void guarda_el_grafo_en_xml(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarda_el_grafo_en_xml


    JFileChooser chooser = new JFileChooser();

    File fichero = null;
    chooser.addChoosableFileFilter(new FiltroFichero());
    chooser.setSelectedFile(new File(".xml"));
    int returnVal = chooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        fichero = chooser.getSelectedFile();
        Xml_creator generador = new Xml_creator();
        Grafo g = panel.getGrafo();
        generador.generarDocumentoXMLDescarga(g, paneles.getSelectedIndex());
        String textoXML = generador.obtenerTextoXML();
        generador.guardarDocumentoXML(textoXML, fichero);
        System.out.println(textoXML);
    }

}//GEN-LAST:event_guarda_el_grafo_en_xml
private void abre_el_grafo_del_xml(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abre_el_grafo_del_xml

    JFileChooser chooser = new JFileChooser();
    File fichero = null;
    chooser.addChoosableFileFilter(new FiltroFichero());
    int returnVal = chooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        fichero = chooser.getSelectedFile();
        ProcesarXML procesador = new ProcesarXML(fichero);
        panel.setGrafo(procesador.parsearDocumento());

        switch (panel.getTipo_grafo()) {
            case 1:
                GND_S.setSelected(true);
                break;
            case 2:
                GND_C.setSelected(true);
                break;
            case 3:
                GD_S.setSelected(true);
                break;
            case 4:
                GD_C.setSelected(true);
                break;

        }
        switch (procesador.getRepresentacion()) {

            case 1:
                this.pasar_a_matriz_adyacencia();
                this.paneles.setSelectedIndex(1);
                break;
            case 2:
                this.pasar_a_matriz_incidecia();
                this.paneles.setSelectedIndex(2);

                break;


        }
    }

}//GEN-LAST:event_abre_el_grafo_del_xml

private void llama_al_recorrido_profundida_del_grafo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llama_al_recorrido_profundida_del_grafo
    panel.recorrido_profundida();
}//GEN-LAST:event_llama_al_recorrido_profundida_del_grafo

private void llama_al_recorrido_anchura_del_grafo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llama_al_recorrido_anchura_del_grafo
    panel.recorrido_anchura();
}//GEN-LAST:event_llama_al_recorrido_anchura_del_grafo

private void crea_nueno_grafo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crea_nueno_grafo
    panel.setGrafo(new Grafo());
    tipos.clearSelection();
    table_incide1.eliminar_All();
    table_panel1.eliminar_All();
}//GEN-LAST:event_crea_nueno_grafo

private void verifico_si_conexo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifico_si_conexo
    panel.conexo();
}//GEN-LAST:event_verifico_si_conexo

private void existe_algun_ciclo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existe_algun_ciclo
panel.existen_ciclo();
}//GEN-LAST:event_existe_algun_ciclo

private void adios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adios
    System.exit(0);
}//GEN-LAST:event_adios

private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
}//GEN-LAST:event_jMenu7ActionPerformed

private void numero_de_vertices(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_de_vertices
    int i = this.panel.getGrafo().size_vertice();
    JOptionPane.showMessageDialog(this, "Existen " + i + " Vertices");
}//GEN-LAST:event_numero_de_vertices

private void numero_de_aristas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_de_aristas
    int i = this.panel.getGrafo().size_arista();
    JOptionPane.showMessageDialog(this, "Existen " + i + " Aristas");
}//GEN-LAST:event_numero_de_aristas

private void calculo_la_exentricidad_del_vertice(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculo_la_exentricidad_del_vertice
    panel.exentricidad();
}//GEN-LAST:event_calculo_la_exentricidad_del_vertice

private void el_diametro_del_grafo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el_diametro_del_grafo
    panel.diametro_grafo();
}//GEN-LAST:event_el_diametro_del_grafo

private void la_distancia_entre_2_vertices(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la_distancia_entre_2_vertices
    panel.camino_entre_nodo();
}//GEN-LAST:event_la_distancia_entre_2_vertices

private void busco_vertice_con_ese_grado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busco_vertice_con_ese_grado
    panel.nodo_con_grado();
}//GEN-LAST:event_busco_vertice_con_ese_grado

private void verifico_si_hay_un_camino_entre_2_vertice(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifico_si_hay_un_camino_entre_2_vertice
    panel.camino_entre_nodo();
}//GEN-LAST:event_verifico_si_hay_un_camino_entre_2_vertice

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GD_C;
    private javax.swing.JRadioButton GD_S;
    private javax.swing.JRadioButton GND_C;
    private javax.swing.JRadioButton GND_S;
    private javax.swing.JMenu Recorridos;
    private javax.swing.JMenu Recorridos1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private proyecto_grafo.Panel_dibujo panel;
    private javax.swing.JTabbedPane paneles;
    private proyecto_grafo.table_incidencia table_incide1;
    private proyecto_grafo.tabla_adyacencia table_panel1;
    private javax.swing.JTextArea text;
    private javax.swing.ButtonGroup tipos;
    // End of variables declaration//GEN-END:variables

    private void pasar_a_matriz_adyacencia() {
       table_panel1.eliminar_All();//elimino todo los elemento de la matrices
        Grafo g = panel.getGrafo();//saco el grafo del panel
        data_fila[] dato = new data_fila[g.size_vertice()];//hago de una arreglo de vectores 
        for (int i = 0; i < g.size_vertice(); i++) {//estructuras de datos
            dato[i] = new data_fila();
        }

        for (int i = 0; i < g.size_vertice(); i++) {
            Vertices A = g.get_vertices(i);
            dato[i].setNombre(A.getNombre());
            for (int j = 0; j < g.size_vertice(); j++) {
                if (j != i) {
                    Vertices B = g.get_vertices(j);
                    int peso =A.adyacencia(B);
                    if (peso != Integer.MIN_VALUE) {
                        dato[i].setArry(j, peso);
                    }

                }
            }
            table_panel1.add(dato[i]);
        }
    }

    private void pasar_a_matriz_incidecia() {
         this.table_incide1.eliminar_All();//elimino todo los elemento de la matrices
        Grafo g = panel.getGrafo();//saco el grafo del panel
        data_fila[] dato = new data_fila[g.size_vertice()];//hago de una arreglo de vectores 
        
        for (int i = 0; i < g.size_vertice(); i++) {//estructuras de datos
            dato[i] = new data_fila(g.get_vertices(i).getNombre());
        }
        for(int i =0;i<g.size_arista();i++){          
            String nombre = g.get_arista(i).getOrigen().getNombre();
            String nombre_0 = g.get_arista(i).getFin().getNombre();
            table_incide1.add_columnNames(nombre + "->" + nombre_0);
        }
        int tipo =this.panel.getTipo_grafo();
        if(tipo==1|tipo==2){            
           
            for (int i = 0; i < g.size_arista(); i++) {
                Arista A = g.get_arista(i);
                for (int j = 0; j < g.size_vertice(); j++) {
                    Vertices B = g.get_vertices(j);
                    if (A.getOrigen().equals(B)) {
                        dato[j].setArry(i, 1);
                    } else if (A.getFin().equals(B)) {
                         dato[j].setArry(i, 1);
                    }
                  
                }
            }

           
        }else if(tipo==3|tipo==4){
        
          for (int i = 0; i < g.size_arista(); i++) {
                Arista A = g.get_arista(i);
                for (int j = 0; j < g.size_vertice(); j++) {
                    Vertices B = g.get_vertices(j);
                    if (A.getOrigen().equals(B)) {                        
                        dato[j].setArry(i, -1);
                    } else if (A.getFin().equals(B)) {
                         dato[j].setArry(i, 1);
                    }
                  
                }
               
            }
        
        }
        for (int j = 0; j < g.size_vertice(); j++) {
            table_incide1.add(dato[j]);
        }
    }

}
